### ISSUE TITLE
Traces below the pots

### ISSUE THREAD

**Issue by Yulquen** [mzourack/QUAAD#2]
Hi,

thanks for sharing your design. FYI I just noticed that there are many traces just below the pots, see below on the picture.

As the pots could me slighly moving and scratch the mask, it could create a shortcut.
 
![PXL_20230125_161506719 MP](https://user-images.githubusercontent.com/4542831/214618160-540a8c93-ef8c-4068-ba2d-e2571e0d81c4.jpg)

Thx

**Comment by mzourack** [comment]
Hey there,
really appreciate the feedback - sounds like a good point, never saw anyone bringing this up.
As the pots are supposed to be tightly attached to the panel with a nut, I don't see them being able to move at all, the module is really stiff.
Anyway, this is something I'll probably be watching out for from now on, I can see it being a problem in some cases.
Hope your build goes smooth!

**Comment by Yulquen** [comment]
I remember one another build where they recommended to put Kapton tape below the pots because they had the issue once.
